[package]
name = "apbf"
version = "0.2.0"
authors = ["timvisee <tim@visee.me>", "robsteward <robinscharf@gmail.com", "psarna"]
edition = "2021"
description = "Tool to brute force Android security pattern through TWRP recovery"

[dependencies]
itertools = "0.10"
pbr = "1.0"
took = "0.1"